FROM openjdk:11-slim-buster
# RUN apt-get update && apt-get -y install python3-pip
LABEL maintainer='devsetgo'
LABEL github_repo='https://github.com/devsetgo/camunda-bpm-run'
EXPOSE 8080
COPY  /bpm_run /bpm
WORKDIR /bpm
RUN useradd -m -r bpmuser && \
    chown -R bpmuser /bpm
USER bpmuser
# Evironment Variables
ENV DB_URL='jdbc:h2:./camunda-h2-test-production/process-engine;TRACE_LEVEL_FILE=0;DB_CLOSE_ON_EXIT=FALSE'
ENV DB_DRIVER='org.h2.Driver'
ENV DB_USERNAME='sa'
ENV DB_PASSWORD='sa'
ENV REST_AUTH_ENABLED=true
# ENV ENABLE_PASSWORD_POLICY=true
# ENV APPLICATION_NAME='Camunda-Engine'
# ENV CAMUNDA_LOGGING_LEVEL='INFO'
# ENV COOKIE_SECURE=true
# ENV COOKIE_HTTP_ONLY=true
# ENV AUTHORIZATION_ENABLED=true
CMD ["./start.sh", "--production"]
